name: Generate Commit Graph (git-graph SVG)

on:
  workflow_dispatch:
    inputs:
      since_date:
        description: 'Start date (e.g. 2024-01-01) for included commits'
        required: false
        default: ''
        type: string

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install git-graph
        run: cargo install git-graph

      - name: Generate commit graph SVG
        run: |
          # set -e
          
          # Parameters
          REPO_PATH=.
          
          # Install Rust if not present
          if ! command -v cargo >/dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            export PATH="$HOME/.cargo/bin:$PATH"
          fi
          
          # Install git-graph
          if ! command -v git-graph >/dev/null; then
            cargo install git-graph
          fi
          
          cd "$REPO_PATH"
          
          # Build git-graph arguments
          args=("--svg" "-o" "commit-graph.svg" "--show-authors" "--show-branches" "--show-merges" "--show-dates" "--width" "2048")
          if [[ -n "${{ github.event.inputs.since_date }}" ]]; then
            args+=("--since" "${{ github.event.inputs.since_date }}")
          fi
          
          # Generate SVG graph
          git-graph "${args[@]}"
          echo "Generated commit-graph.svg"

      - name: Upload SVG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-graph
          path: commit-graph.svg
