name: Generate Commit Graph (git-sim)

on:
  workflow_dispatch:
    inputs:
      commit_count:
        description: 'Number of recent commits per branch (default: 25, "all" for all commits)'
        required: false
        default: '25'
        type: string

jobs:
  git-sim-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure all commits/branches are available

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install git-sim dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install git-sim

      - name: Generate git commit graph image with git-sim
        run: |
          # Default output is PNG, editable via -o argument
          # Show all branches; commit count is configurable
          if [ "${{ github.event.inputs.commit_count }}" = "all" ]; then
            git-sim log --all -o commit-graph.png
          else
            git-sim log --all -n "${{ github.event.inputs.commit_count }}" -o commit-graph.png
          fi
          echo "Generated commit-graph.png"

      - name: Upload commit graph PNG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-graph
          path: commit-graph.png
